//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comp2007_GameTracker_By_RishabhAndJosh.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamesPlayed
    {
        public int GamesPlayedID { get; set; }
        public System.DateTime DatePlayed { get; set; }
        public int Game { get; set; }
        public int TeamA { get; set; }
        public int TeamB { get; set; }
        public decimal TotalPointsScored { get; set; }
        public int NumberOfSpectators { get; set; }
        public int WinningTeam { get; set; }
        public decimal TeamA_Scores { get; set; }
        public decimal TeamB_Scores { get; set; }
        public decimal TotalPointsAllowed { get; set; }
    
        public virtual Game Game1 { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        public virtual Team Team2 { get; set; }
    }
}
